package workflow

// The pure, testable half of §17's DIFF step: read the harness, read the built
// repo, and say what does not line up. No database, no network, no blackboard —
// everything here is a function of bytes on disk, which is what makes it
// checkable without a running stack.
//
// WHAT "COMPARE CODE TO THE DESIGN" CAN AND CANNOT BE
//
// §17.4 calls the comparator "the only genuinely new logic, and it is bounded".
// The bound is worth stating exactly, because an unbounded reading of it turns
// into a static analyser for every language:
//
//	 checkable  — does a criterion's own Verify command pass in the built repo
//	 checkable  — does a path the design names appear in the repo's source
//	 checkable  — does a path the repo declares appear nowhere in the design
//	 NOT here   — whether the implementation is correct, idiomatic, or complete
//
// Every finding is a QUESTION ROUTED TO A HUMAN EXPERT, never an automatic
// write. That is what makes a heuristic acceptable here: a false positive costs
// one question in the amendment queue, not a corrupted design.

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

// ============================================================
// ACCEPTANCE.md
// ============================================================

// acceptanceCriterion is one parsed AC-* entry.
type acceptanceCriterion struct {
	ID string
	// Owner is the expert NAME as written in the file. Unreliable on its own:
	// acceptanceLineRe (authoring.go) captures owner as \S+, so "Unlimited Go"
	// arrives as "Unlimited". Resolution therefore keys on SectionPath first —
	// that string is machine-generated by DesignSectionStore and matches
	// workflow_design_sections exactly — and falls back to Owner only when the
	// section is unknown.
	Owner       string
	SectionPath string
	Statement   string
	Verify      string
	DoneWhen    string
}

var (
	acStatementRe = regexp.MustCompile(`(?mi)^\s*Statement:\s*(.+)$`)
	acVerifyRe    = regexp.MustCompile(`(?mi)^\s*Verify:\s*(.+)$`)
	acDoneWhenRe  = regexp.MustCompile(`(?mi)^\s*Done when:\s*(.+)$`)
)

// parseAcceptance reads every criterion out of an ACCEPTANCE.md body.
//
// Reuses acceptanceLineRe and acceptance2VerifyBlock from authoring.go rather
// than writing a second parser for the same file. documentCheck already gates
// on that exact heading shape at authoring time, so any file that passed the
// document check parses here — one format, one regexp, one place to change it.
func parseAcceptance(content string) []acceptanceCriterion {
	var out []acceptanceCriterion
	for _, m := range acceptanceLineRe.FindAllStringSubmatch(content, -1) {
		ac := acceptanceCriterion{ID: m[1], Owner: m[2], SectionPath: m[3]}
		block := acceptance2VerifyBlock(content, ac.ID)
		if g := acStatementRe.FindStringSubmatch(block); g != nil {
			ac.Statement = strings.TrimSpace(g[1])
		}
		if g := acVerifyRe.FindStringSubmatch(block); g != nil {
			ac.Verify = strings.TrimSpace(g[1])
		}
		if g := acDoneWhenRe.FindStringSubmatch(block); g != nil {
			ac.DoneWhen = strings.TrimSpace(g[1])
		}
		out = append(out, ac)
	}
	return out
}

// ============================================================
// Verify commands — parsing and permission
// ============================================================

// verifyAllowedCommands is the set of executables a Verify line may name.
//
// Why an allowlist at all:
//
// A Verify line is text a language model wrote into a markdown file. Running it
// means executing model-authored strings inside the api container. The existing
// Aider path already runs `go build` and `npm run build` in a workspace, so
// running build tooling is not new — running an ARBITRARY first word is. An
// allowlist keeps the capability (check the build, run the tests) and removes
// the category (delete files, reach the network, start a shell).
//
// Absent on purpose: sh, bash, curl, wget, rm, chmod, ssh, docker, git. Any of
// those in a Verify line is a design-document defect worth reporting, not a
// command worth running.
var verifyAllowedCommands = map[string]bool{
	"go": true, "gofmt": true, "golangci-lint": true,
	"npm": true, "npx": true, "yarn": true, "pnpm": true, "node": true,
	"python": true, "python3": true, "pytest": true,
	"make": true,
	"grep": true, "test": true, "ls": true, "cat": true,
}

// shellOperators are the characters that mean something to a shell and nothing
// to exec. Rejected only OUTSIDE quotes.
//
// Why only outside: `go test -run 'TestA|TestB'` is an ordinary, correct
// command, and a blanket ban on '|' would report it as unrunnable. Inside
// quotes the character is part of one argument and, because nothing here ever
// invokes a shell, it stays part of that argument.
//
// Glob characters (* ? [ ]) and '$' are deliberately NOT rejected: with no
// shell in the chain they are passed through as literal bytes, so the worst
// they do is fail to match.
const shellOperators = "|&;<>`\n\r"

// splitVerifyCommand turns a Verify line into argv.
//
// Returns a reason instead of an error when the command may not run, because
// the caller's next move is identical for every reason: record the criterion as
// unverifiable WITH that reason and keep going. verify.go established that a
// check which could not run is neither a pass nor a failure; a Verify line that
// cannot safely run is the same third thing.
func splitVerifyCommand(line string) (argv []string, reason string) {
	line = strings.TrimSpace(line)
	if line == "" {
		return nil, "the criterion has no Verify command"
	}

	var args []string
	var cur strings.Builder
	quote := rune(0)
	started := false

	for _, r := range line {
		switch {
		case quote != 0:
			if r == quote {
				quote = 0
				continue
			}
			cur.WriteRune(r)
		case r == '\'' || r == '"':
			quote = r
			started = true // "" is a real, empty argument
		case r == ' ' || r == '\t':
			if started {
				args = append(args, cur.String())
				cur.Reset()
				started = false
			}
		case strings.ContainsRune(shellOperators, r):
			return nil, fmt.Sprintf("the Verify command needs a shell (it contains %q), so it was not run", string(r))
		default:
			cur.WriteRune(r)
			started = true
		}
	}
	if quote != 0 {
		return nil, "the Verify command has an unclosed quote"
	}
	if started {
		args = append(args, cur.String())
	}
	if len(args) == 0 {
		return nil, "the criterion has no Verify command"
	}

	cmd := args[0]
	if strings.ContainsAny(cmd, "/\\") {
		return nil, fmt.Sprintf("the Verify command runs %q by path; only a plain allowed command name may be run", cmd)
	}
	if !verifyAllowedCommands[cmd] {
		return nil, fmt.Sprintf("%q is not in the set of commands allowed to run against a client repository", cmd)
	}
	return args, ""
}

// ============================================================
// Contract items — endpoints and tables
// ============================================================

// contractItem is one thing the design promises, or one thing the code
// declares. The same type for both sides so the comparison is a set difference
// rather than two shapes glued together.
type contractItem struct {
	Kind   string `json:"kind"`   // "endpoint" | "table"
	Key    string `json:"key"`    // canonical form; the identity used for comparison
	Source string `json:"source"` // file it was found in, for the routing question
}

var (
	// endpointRe matches an HTTP method next to a path, in every shape the
	// design and the generated code actually use:
	//
	//	| POST | /boards/{id}/archive |     markdown table, method in its own column
	//	POST /boards/{id}/archive           markdown prose or a list item
	//	r.POST("/boards/:id/archive", h)    gin
	//	@app.post("/boards/{id}/archive")   fastapi
	//	router.post('/boards/:id/archive')  express
	//	POST -> /boards/{id}/archive        arrow notation
	//
	// The separator class is what makes one pattern cover all six. The pipe in
	// it is not decoration: the FIRST version of this regexp omitted it, and a
	// design that writes its API as a markdown table with Method and Path in
	// separate columns — the shape §3.3 uses for the module map, so the shape an
	// expert copies — matched nothing at all. Every designed endpoint would then
	// have been reported as "the code declares an endpoint the design never
	// defined", with the real design sitting right there. Caught by running the
	// extractor on a table, not by reading it.
	//
	// Spring's @PostMapping is NOT matched: "POST" there is not followed by a
	// word boundary, so \bPOST\b cannot see it. Named as a known gap rather than
	// papered over with a looser pattern that would match the word "post" in
	// prose.
	endpointRe = regexp.MustCompile(`(?i)\b(GET|POST|PUT|PATCH|DELETE)\b["'\s(\[,=:|>-]*(/[A-Za-z0-9_./:{}$-]*)`)

	// createTableRe matches SQL DDL in either a design document or a migration.
	createTableRe = regexp.MustCompile(`(?i)\bCREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?"?([a-zA-Z_][a-zA-Z0-9_]*)"?`)

	pathParamRe = regexp.MustCompile(`^[:{$<].*|.*}$`)
)

// canonEndpoint reduces one method+path to a comparable key.
//
// The whole point: the design writes /boards/{id}/archive, gin writes
// /boards/:id/archive, and they are the same endpoint. Every parameter segment
// collapses to {} so the two sides can be compared as strings. Without this the
// "invented endpoint" list would contain every endpoint in the design, which is
// worse than no report at all.
func canonEndpoint(method, path string) string {
	method = strings.ToUpper(method)

	path = strings.TrimSpace(path)
	if i := strings.IndexAny(path, "?#"); i >= 0 {
		path = path[:i]
	}
	// Trailing punctuation picked up from prose or from a code literal.
	path = strings.TrimRight(path, ".,:;\"')")
	if path != "/" {
		path = strings.TrimSuffix(path, "/")
	}
	if path == "" || path == "/" {
		return "" // a bare slash is prose, not an endpoint
	}

	segs := strings.Split(strings.TrimPrefix(path, "/"), "/")
	kept := make([]string, 0, len(segs))
	for _, s := range segs {
		if s == "" {
			continue
		}
		if pathParamRe.MatchString(s) {
			kept = append(kept, "{}")
			continue
		}
		kept = append(kept, s)
	}
	if len(kept) == 0 {
		return ""
	}
	// An endpoint made only of parameters is not a real route; it is almost
	// always a fragment of prose like "DELETE /{id}" used as an example.
	allParams := true
	for _, s := range kept {
		if s != "{}" {
			allParams = false
			break
		}
	}
	if allParams {
		return ""
	}
	return method + " /" + strings.Join(kept, "/")
}

// extractContract pulls every endpoint and table out of one text body.
func extractContract(text, source string) []contractItem {
	seen := map[string]bool{}
	var out []contractItem

	for _, m := range endpointRe.FindAllStringSubmatch(text, -1) {
		key := canonEndpoint(m[1], m[2])
		if key == "" {
			continue
		}
		id := "endpoint\x00" + key
		if seen[id] {
			continue
		}
		seen[id] = true
		out = append(out, contractItem{Kind: "endpoint", Key: key, Source: source})
	}

	for _, m := range createTableRe.FindAllStringSubmatch(text, -1) {
		key := strings.ToLower(m[1])
		id := "table\x00" + key
		if seen[id] {
			continue
		}
		seen[id] = true
		out = append(out, contractItem{Kind: "table", Key: key, Source: source})
	}

	return out
}

// ============================================================
// Reading the two sides
// ============================================================

// harnessFileNames are the protocol files the harness puts at a repo root.
// Listed here because the CLIENT REPO CONTAINS THEM: the export pushes the
// harness, so the built repo has final.md, ACCEPTANCE.md, DECISIONS.md,
// CLAUDE.md and design/ sitting in it.
//
// This is the single most important exclusion in this file. Without it every
// endpoint the design names is trivially "present in the repo" — because the
// design document IS in the repo — and the unbuilt list is empty forever. The
// report would say everything was built, always.
var harnessFileNames = map[string]bool{
	finalMD:      true,
	acceptanceMD: true,
	decisionsMD:  true,
	"CLAUDE.md":  true,
}

// repoScanSkipDirs are directories never scanned, in the built repo or in the
// harness. Same list internal/repo uses for its sync (skipDirs there), plus
// "design" — the harness's own section folder.
var repoScanSkipDirs = map[string]bool{
	".git": true, "node_modules": true, "vendor": true,
	"dist": true, "build": true, ".next": true,
	"__pycache__": true, ".venv": true, "venv": true,
	"target": true, "bin": true, "obj": true,
	"design": true,
}

// repoScanExtensions are the file types read when looking for what the code
// declares.
//
// Markdown is absent, deliberately. The question this scan answers is "was it
// BUILT", and a design document describing an endpoint is not an endpoint. It
// also removes the harness-echo problem at the root: even a design section
// copied somewhere unexpected in the repo cannot make an unbuilt endpoint look
// built.
var repoScanExtensions = map[string]bool{
	".go": true, ".py": true, ".ts": true, ".tsx": true, ".js": true, ".jsx": true,
	".java": true, ".rb": true, ".rs": true, ".php": true, ".cs": true,
	".sql": true, ".yaml": true, ".yml": true, ".json": true,
}

const (
	// scanMaxFileBytes skips a file larger than this. A generated bundle or a
	// checked-in dump is megabytes of noise for this purpose.
	scanMaxFileBytes = 512 * 1024
	// scanMaxFiles bounds total work on a large repository.
	scanMaxFiles = 5000
)

// scanRepoContract walks a built repository and returns what its code declares.
//
// skipRootHarness excludes the harness files at the repository ROOT only —
// a nested file that merely shares a name (some other CLAUDE.md deep in a
// subtree) is real repository content and is scanned.
func scanRepoContract(root string) ([]contractItem, int, error) {
	seen := map[string]bool{}
	var out []contractItem
	filesRead := 0

	err := filepath.Walk(root, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return nil // unreadable entry: skip it, keep walking
		}
		if info.IsDir() {
			if path == root {
				return nil
			}
			if repoScanSkipDirs[info.Name()] || strings.HasPrefix(info.Name(), ".") {
				return filepath.SkipDir
			}
			return nil
		}
		if filesRead >= scanMaxFiles {
			return filepath.SkipAll
		}
		rel, relErr := filepath.Rel(root, path)
		if relErr != nil {
			return nil
		}
		if !strings.Contains(rel, string(filepath.Separator)) && harnessFileNames[info.Name()] {
			return nil
		}
		if !repoScanExtensions[strings.ToLower(filepath.Ext(path))] {
			return nil
		}
		if info.Size() > scanMaxFileBytes {
			return nil
		}
		data, readErr := os.ReadFile(path)
		if readErr != nil {
			return nil
		}
		filesRead++
		for _, item := range extractContract(string(data), rel) {
			id := item.Kind + "\x00" + item.Key
			if seen[id] {
				continue
			}
			seen[id] = true
			out = append(out, item)
		}
		return nil
	})
	if err != nil {
		return nil, filesRead, fmt.Errorf("scan repository: %w", err)
	}
	return out, filesRead, nil
}

// readDesignContract reads the spine and every assigned section file from the
// merged harness workspace, and returns what the design promises.
//
// Source is kept per item because the routing step needs it: a missing endpoint
// first named in design/20-unlimited-go.md is that expert's question to answer,
// and the section path is the reliable way to find which expert that is.
func readDesignContract(mainPath string, sectionPaths []string) ([]contractItem, error) {
	seen := map[string]bool{}
	var out []contractItem

	files := append([]string{finalMD}, sectionPaths...)
	readAny := false
	for _, rel := range files {
		data, err := os.ReadFile(filepath.Join(mainPath, rel))
		if err != nil {
			continue // a section not yet authored is absent, not an error
		}
		readAny = true
		for _, item := range extractContract(string(data), rel) {
			id := item.Kind + "\x00" + item.Key
			if seen[id] {
				continue // first file to name it owns it
			}
			seen[id] = true
			out = append(out, item)
		}
	}
	if !readAny {
		return nil, fmt.Errorf("%w (no readable design files in %s)", ErrNoHarness, mainPath)
	}
	return out, nil
}

// diffContract compares the two sides.
//
// Both directions matter and they answer different questions: missingInCode is
// "we designed it, is it still wanted?", notInDesign is "they built it, should
// the contract adopt it?". §17.5 routes them to different people for exactly
// that reason.
func diffContract(design, code []contractItem) (missingInCode, notInDesign []contractItem) {
	codeKeys := map[string]bool{}
	for _, c := range code {
		codeKeys[c.Kind+"\x00"+c.Key] = true
	}
	designKeys := map[string]bool{}
	for _, d := range design {
		designKeys[d.Kind+"\x00"+d.Key] = true
	}

	for _, d := range design {
		if !codeKeys[d.Kind+"\x00"+d.Key] {
			missingInCode = append(missingInCode, d)
		}
	}
	for _, c := range code {
		if !designKeys[c.Kind+"\x00"+c.Key] {
			notInDesign = append(notInDesign, c)
		}
	}
	return missingInCode, notInDesign
}
